// <auto-generated />
namespace passion_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class onemore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onemore));
        
        string IMigrationMetadata.Id
        {
            get { return "202002142156298_one more"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
